"""Build helper: expand the bundled attack-dictionary to ~5000+ entries.

This script is run once at authoring time to generate
`password_dictionary.txt`. It is NOT invoked at Lambda runtime — the
generated file is a build artefact and is committed to the repository.

Source corpora referenced by name (entries listed below are the public
dictionary patterns, not user PII):
  - SecLists Probable-v2-Top1575
  - SecLists Common-Credentials/10-million-password-list-top-* (CC-BY-3.0)
  - Cowrie operator writeups (Trustwave, SANS ISC, Akamai SIRT)
  - Default-credential lists for common router/IoT appliances (CIRCL.lu)

Usage:
    python build_dictionary.py [output_path]
"""

from __future__ import annotations

import sys
from pathlib import Path

HEADER = """\
# Attempted-password attack dictionary for the Honeypot Visualizer Dashboard.
# ADR-005 — only attempted passwords matching an entry here are surfaced
# verbatim on the public dashboard; non-matches are redacted to <filtered:len=N>.
#
# This file is GENERATED by build_dictionary.py from canonical attack-dictionary
# patterns (see the script's docstring for source-corpus references).
# Do not hand-edit; regenerate with `python build_dictionary.py > password_dictionary.txt`.
#
# Format: one literal password per line. Lines beginning with '#' are
# ignored. Whitespace is stripped. Entries are case-sensitive.
"""

# Top 10 of every published common-password list shows up here.
TOP_RAW = [
    "123456",
    "password",
    "12345678",
    "qwerty",
    "123456789",
    "12345",
    "1234",
    "111111",
    "1234567",
    "dragon",
    "123123",
    "baseball",
    "abc123",
    "football",
    "monkey",
    "letmein",
    "shadow",
    "master",
    "666666",
    "qwertyuiop",
    "123321",
    "mustang",
    "1234567890",
    "michael",
    "654321",
    "superman",
    "1qaz2wsx",
    "7777777",
    "121212",
    "000000",
    "qazwsx",
    "123qwe",
    "killer",
    "trustno1",
    "jordan",
    "jennifer",
    "zxcvbnm",
    "asdfgh",
    "hunter",
    "buster",
    "soccer",
    "harley",
    "batman",
    "andrew",
    "tigger",
    "sunshine",
    "iloveyou",
    "2000",
    "charlie",
    "robert",
    "thomas",
    "hockey",
    "ranger",
    "daniel",
    "starwars",
    "112233",
    "george",
    "computer",
    "michelle",
    "jessica",
    "pepper",
    "1111",
    "zxcvbn",
    "555555",
    "11111111",
    "131313",
    "freedom",
    "777777",
    "pass",
    "maggie",
    "159753",
    "aaaaaa",
    "ginger",
    "princess",
    "joshua",
    "cheese",
    "amanda",
    "summer",
    "love",
    "ashley",
    "6969",
    "nicole",
    "chelsea",
    "biteme",
    "matthew",
    "access",
    "yankees",
    "987654321",
    "dallas",
    "austin",
    "thunder",
    "taylor",
    "matrix",
    "raspberry",
    "raspberrypi",
    "ubuntu",
    "debian",
    "oracle",
    "postgres",
    "mysql",
    "default",
    "guest",
    "test",
    "admin",
    "root",
    "toor",
    "service",
    "support",
    "manager",
    "operator",
    "user",
    "demo",
    "public",
    "secret",
    "internet",
    "network",
    "intranet",
    "home",
    "office",
    "backup",
    "server",
    "linux",
    "windows",
    "redhat",
    "fedora",
    "centos",
    "kali",
    "mint",
    "arch",
    "suse",
    "huawei",
    "cisco",
    "juniper",
    "xfinity",
    "comcast",
    "verizon",
    "google",
    "Microsoft",
    "Apple",
    "Amazon",
    "AWS",
    "Azure",
    "VMware",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Git",
    "GitLab",
    "GitHub",
]

# Bases used for the COMBINATORIAL expansion below.
BASES_LOWER = [
    "admin",
    "root",
    "password",
    "welcome",
    "default",
    "secret",
    "login",
    "system",
    "network",
    "server",
    "master",
    "support",
    "service",
    "manager",
    "operator",
    "backup",
    "guest",
    "test",
    "demo",
    "temp",
    "change",
    "qwerty",
    "abc",
    "super",
    "power",
    "dev",
    "prod",
    "linux",
    "windows",
    "mysql",
    "oracle",
    "postgres",
    "mongo",
    "redis",
    "nginx",
    "apache",
    "docker",
    "jenkins",
    "cisco",
    "huawei",
    "google",
    "amazon",
    "azure",
    "ubuntu",
    "centos",
    "debian",
    "raspberry",
    "pi",
    "iot",
    "hello",
    "monitor",
    "secure",
    "private",
    "public",
    "office",
    "remote",
    "host",
    "ssh",
    "telnet",
    "router",
    "switch",
    "firewall",
]

BASES_TITLE = [b.title() if not b.isupper() else b for b in BASES_LOWER]

NUM_SUFFIXES = [
    "1",
    "12",
    "123",
    "1234",
    "12345",
    "123456",
    "1234567",
    "12345678",
    "123456789",
    "1234567890",
]
SYMBOL_SUFFIXES = ["!", "@", "#", "!@#", "!@#$"]
YEAR_SUFFIXES = [str(y) for y in range(2020, 2027)]

KEYBOARD_WALKS = [
    "qwerty",
    "qwertyuiop",
    "asdfgh",
    "asdfghjkl",
    "zxcvbn",
    "zxcvbnm",
    "1qaz",
    "2wsx",
    "3edc",
    "4rfv",
    "5tgb",
    "6yhn",
    "7ujm",
    "8ik,",
    "9ol.",
    "0p;/",
    "1qaz2wsx",
    "1qaz2wsx3edc",
    "1qaz2wsx3edc4rfv",
    "qazwsx",
    "qazwsxedc",
    "qazwsxedcrfv",
    "1q2w3e",
    "1q2w3e4r",
    "1q2w3e4r5t",
    "1q2w3e4r5t6y",
    "1q2w3e4r5t6y7u",
    "qweasd",
    "qweasdzxc",
    "qweasdzxc!@#",
    "qweasdzxcvbn",
    "asdfqwer",
    "qwerasdf",
    "qwerasdfzxcv",
    "abcabc",
    "abcabcabc",
    "qwerty!",
    "qwerty1!",
    "qwerty12!",
    "qwerty123!",
    "qwerty1!@#",
    "asdf!",
    "asdf1!",
    "asdf12!",
    "asdf123!",
    "asdf1!@#",
    "1234!",
    "12345!",
    "123456!",
    "1234567!",
    "12345678!",
    "abcd1234",
    "abcd12345",
    "abcd123456",
    "abcd!@#$",
    "qaz!@#",
    "qaz1!@#",
    "qaz12!@#",
    "qaz123!@#",
    "1q2w!@",
    "1q2w3e!@#",
    "1q2w3e4r!@#$",
    "qwerasdfzxcv",
    "qwerasdfzxcv1234",
    "qwerasdfzxcv!@#$",
    "abc!@#",
    "abc1!@#",
    "abc12!@#",
    "abc123!@#",
]

# Default-credential pairs from public IoT/router default lists, expressed
# as common login@admin patterns (admin@admin, root@root, etc.).
COMMON_PAIRED = [
    "admin/admin",
    "admin/password",
    "admin/12345",
    "admin/123456",
    "admin/admin123",
    "admin/admin1234",
    "admin/admin12345",
    "admin/admin123456",
    "admin/changeme",
    "admin/Changeme1",
    "root/root",
    "root/toor",
    "root/admin",
    "root/password",
    "root/raspberry",
    "root/raspberrypi",
    "root/changeme",
    "guest/guest",
    "test/test",
    "demo/demo",
    "user/user",
    "operator/operator",
    "manager/manager",
    "service/service",
    "support/support",
    "default/default",
    "ftp/ftp",
    "ftp/ftpuser",
    "oracle/oracle",
    "postgres/postgres",
    "mysql/mysql",
    "sa/sa",
    "sa/admin",
    "sa/password",
    "sa/sa123",
    "mongo/mongo",
    "mongo/admin",
    "redis/redis",
    "redis/foobared",
    "elastic/elastic",
    "elastic/changeme",
    "kibana/kibana",
    "pi/raspberry",
    "pi/raspberrypi",
    "pi/pi",
    "pi/admin",
    "ubuntu/ubuntu",
    "ubuntu/admin",
    "ubuntu/password",
    "ubuntu/123456",
    "centos/centos",
    "debian/debian",
    "huawei/huawei",
    "cisco/cisco",
    "juniper/juniper",
]


def expand() -> list[str]:
    out: set[str] = set()
    out.update(TOP_RAW)
    out.update(KEYBOARD_WALKS)
    out.update(COMMON_PAIRED)

    # base + numeric / symbolic / year suffix
    for base_set in (BASES_LOWER, BASES_TITLE):
        for base in base_set:
            out.add(base)
            for sfx in NUM_SUFFIXES:
                for join in ("", "@"):
                    out.add(f"{base}{join}{sfx}")
            for sym in SYMBOL_SUFFIXES:
                out.add(f"{base}{sym}")
                out.add(f"{base}123{sym}")
            for year in YEAR_SUFFIXES:
                out.add(f"{base}{year}")
                out.add(f"{base}@{year}")

    # Common leet-speak substitutions on a small core set
    leet_core = ["password", "admin", "root", "letmein", "welcome", "secret"]
    leet_subs = {"a": "@", "i": "1", "o": "0", "e": "3", "s": "$"}
    for base in leet_core:
        for char, sub in leet_subs.items():
            if char in base:
                out.add(base.replace(char, sub))
                out.add(base.replace(char, sub).title())
        # Multi-sub flavour
        leet = base
        for char, sub in leet_subs.items():
            leet = leet.replace(char, sub)
        out.add(leet)
        out.add(leet + "!")
        out.add(leet + "1")
        out.add(leet + "123")

    # Pure number rotations 4-12 digits
    for length in range(4, 13):
        out.add("1" * length)
        out.add("0" * length)
        out.add("9" * length)
        if length >= 6:
            out.add("123456" + "0" * (length - 6))
        if length <= 10:
            out.add("".join(str(i % 10) for i in range(1, length + 1)))
            out.add("".join(str((10 - i) % 10) for i in range(1, length + 1)))

    # Concatenations: base + base
    repeat_bases = ["admin", "root", "password", "qwerty", "abc", "test"]
    for a in repeat_bases:
        for b in repeat_bases:
            out.add(a + b)
            out.add(a + "_" + b)
            out.add(a + "@" + b)
            out.add(a + "/" + b)

    # Strip blanks defensively
    return sorted(s for s in out if s)


def main() -> int:
    out_path = (
        Path(sys.argv[1])
        if len(sys.argv) > 1
        else Path(__file__).resolve().parent / "password_dictionary.txt"
    )
    seen: set[str] = set()
    lines: list[str] = [HEADER]
    for entry in expand():
        if entry in seen:
            continue
        seen.add(entry)
        lines.append(entry)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(seen)} entries to {out_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
